### ISSUE TITLE
Fix background image URL syntax in speaker card in /layouts/sessions/single.html

### ISSUE THREAD

**Issue by techmannih** [json-schema-org/conference#12]
The background image URL syntax in the speaker card component of the session page (/layouts/sessions/single.html) was not properly formatted, potentially causing broken or incorrectly rendered images. The issue likely stems from improper handling of dynamic templating for the photoURL parameter.

**Comment by DhairyaMajmudar** [comment]
@techmannih you can commit changes realted to other files in  https://github.com/json-schema-org/conference/pull/14 only no need to create a separate PR for other files

**Comment by DhairyaMajmudar** [comment]
> @DhairyaMajmudar Sure, I will. So, I think there’s also no need to raise separate issues for all.

Yeah no need for seprate issue
