### ISSUE TITLE
Return to top button

### ISSUE THREAD

**Issue by pavanydg** [json-schema-org/conference#16]
When a user scrolls to the bottom of the page, we can add a button to return to the top of the page.

**Comment by Gorachand-Senapati** [comment]
@pavanydg bro you solve the issue?

**Comment by DhairyaMajmudar** [comment]
@pavanydg any update on this, if you're facing any issue feel free to ask.

**Comment by pavanydg** [comment]
@DhairyaMajmudar i have raised the pr which adds this feature in this pr #25. Pls review.
