### ISSUE TITLE
Update speakers page

### ISSUE THREAD

**Issue by valeriahhdez** [json-schema-org/conference#22]
Update the [speaker's line-up](https://conference.json-schema.org/sessions/) to reflect the last-minute changes we had during the conference. The full list of speakers is the following:

- JSON Schema for data design and contract, client and code generation by Tom Collins (DVLA, UK Gov)
- IEC Standards: Toward Digital Standards with JSON Schema by Thomas Clark (Octue CEO, conference sponsor)
- Introducing Strands - a JSON Schema repository by Thomas Clark
- JSON Schema: powering FINOS architecture as code by James Gough (FINOS)
- Generic and extensible web of things manager using JSON Schema and AI by Andreas Eberhart (Dashjoin, ambassador)
- High-performance JSON Schema validation in .NET by Matthew Adams (Endjin, TSC member)
- JSON schema and relational databases: bridging the gap by Loic Lefèvre (Oracle)
-Applying software engineering practices to JSON Schemas by Juan Cruz Viotti (Sourcemeta CEO, TSC member)
- The state of JSON schema by Benjamin Granados (Celonis, TSC member)

Also add the slide decks, which are available as PDF files, in this PR. 

If you want to work on this issue, please reach out to Valeria Hernandez on the JSON Schema Slack workspace, so she can share the files with you. 

Thank you.

**Comment by valeriahhdez** [comment]
Yes, you can :D

**Comment by benjagm** [comment]
Please, let's do not remove Neha's talk from the list. We can add James Gough in that position and move Neha as the last session of the day.

**Comment by valeriahhdez** [comment]
> Please, let's do not remove Neha's talk from the list. We can add James Gough in that position and move Neha as the last session of the day.

Ok!

Would you like to ask Neha if she would share her slides to upload them to the website? @benjagm

**Comment by Honyii** [comment]
@techmannih - to add to @valeriahhdez issue description, I hope this is covered too:

1. You can first rename and upload the pdfs to the static folder in a folder called presentations/talks.
2. Add the url of each presentation in the presentation field for each session. Each file has metadata and the metadata field to link the presentation.
