### ISSUE TITLE
Feat: Update sessions page and add presentation links

### ISSUE THREAD

**Issue by Honyii** [json-schema-org/conference#23]
From the concluded conference in Paris, there is a need to add the presentation slides for each speaker and also update the sessions details to display the urls.

**Steps to achieve this feature**
1. Upload all presentation pdfs to the repo - this will be added in the static folder named presentations
2. Update the sessions file for each presentation  - changing the metadata from "presentation: null" to "presentation: {presentation link}"

**Comment by Honyii** [comment]
Yea, I'd close this ticket and drop a comment on Valeria's ticket to cover other use cases.

**Comment by benjagm** [comment]
Thanks @Honyii !
