### ISSUE TITLE
Bug: Broken or Missing Speaker Image URL Handling Across Multiple Templates

### ISSUE THREAD

**Issue by techmannih** [json-schema-org/conference#8]
There is a recurring issue related to the handling of the `photoURL` for speaker images across multiple templates in the project. The issue is present in the following files and templates, where the speaker's image is intended to be rendered with a `background-image` using `photoURL`. However, the `photoURL` variable may not be defined, or is incorrectly handled, which can lead to broken image references.

**Files affected:**
- [x] `/layouts/session.html` #12 
- [ ] `/layouts/sessions/single.html`
- [ ] `/layouts/speakers/single.html`
- [ ] `/themes/devfest-theme-hugo/layouts/partials/schedule-session.html`
- [ ] `/themes/devfest-theme-hugo/layouts/partials/session.html`
- [ ] `/themes/devfest-theme-hugo/layouts/partials/speaker.html`
- [ ] `/themes/devfest-theme-hugo/layouts/sessions/single.html`
- [ ] `/themes/devfest-theme-hugo/layouts/speakers/single.html`

## Problem
The speaker image is rendered using a `background-image` property that is set dynamically via `{{ .Params.photoURL }}`. If the `photoURL` is missing or incorrect, this leads to broken or missing images across multiple pages where speaker profiles are used.

## Objective
Address this issue by implementing checks for missing or invalid `photoURL` and ensure fallbacks or default images are provided where necessary.

**Comment by DhairyaMajmudar** [comment]
Sure go ahead @techmannih 👍🏻

**Comment by DhairyaMajmudar** [comment]
Yup 💯
